config/routes.rb
Rails.application.routes.draw do
root :to => 'sessions#new'
get "/log-in" => "sessions#new"
post "/log-in" => "sessions#create"
get "/log-out" => "sessions#destroy", as: :log_out #custom path

resources :users

resources :clothings do
  resources :comments
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clothing.rb
class Clothing < ApplicationRecord
  has_many :comments
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, :presence => true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :clothing
  belongs_to :user
  # acts_as_votable

  validates :content, :presence => true
end

app/models/comments.rb
class Comment < ApplicationRecord
  belongs_to :clothing
  belongs_to :user
  # acts_as_votable

  validates :content, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password #What this means is that a new instance of User can be created with all of the data from our sign up form and we can store a password on this instance without having a database column back it.
  validates_confirmation_of :password
  validates :email, :uniqueness => true
  validates :email, :presence => true
  validates :password, :presence => true
  before_save :encrypt_password
  has_many :outfits
  has_many :comments


  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    # session[:user_id] = nil 
    #used to reset the user if database drops while user signed in
    @current_user ||= User.find(session[:user_id]) if session[:user_id] # Basically, if session[:user_id] is set, find the User with that id. The @current_user ||= part of the method will cache the current user inside of the @current_user instance variable so we don't have to make a database call each time the method is called.
  end


  helper_method :current_user

  before_filter :require_login

  private
    def require_login
      unless current_user
        redirect_to log_in_path
      end
    end

end

app/controllers/clothings_controller.rb
class ClothingsController < ApplicationController

  def index
    @clothings = Clothing.all
    # @user = current_user      # filtering by user
    # @clothings = @user.clothings
  end

  def show
    @clothing = Clothing.find(params[:id])
    # if params[:upvote]
    #   @answer = Answer.find(params[:upvote])
    #   @answer.liked_by current_user
    #   render :show
    # end
    # if params[:downvote]
    #   @answer = Answer.find(params[:downvote])
    #   @answer.disliked_by current_user
    #   render :show
    # end
  end

  def new
    @clothing = Clothing.new
  end

  def create
    @clothing = Clothing.new(clothing_params)
    @clothing.user_id = session[:user_id]
    if @clothing.save
      flash[:notice] = "Clothing added!"
      redirect_to clothings_path
    else
      render :new
    end
  end

  def edit
    @clothing = Clothing.find(params[:id])
  end

  def update
    @clothing = Clothing.find(params[:id])
    if @clothing.update(clothing_params)
      flash[:notice] = "Clothing updated!"
      redirect_to clothings_path
    else
      render :edit
    end
  end

  def destroy
    @clothing = Clothing.find(params[:id])
    @clothing.destroy
    flash[:notice] = "Clothing deleted!"
    redirect_to clothings_path
  end


  private
    def clothing_params
      params.require(:clothing).permit(:name, :details, :price, :image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
      @clothing = Clothing.find(params[:clothing_id]) # getting id from clothing
      @comment = @clothing.comments.new # maping id/comments/new
    end

    def create
      @clothing = Clothing.find(params[:clothing_id]) # getting id from clothing
      @comment = @clothing.comments.new(comment_params)
      @comment.user_id = current_user.id
      if @comment.clothing.save
        flash[:notice] = "Comment Saved!"
        redirect_to clothing_path(@comment.clothing)
      else
        flash[:notice] = "Comment not Saved!"
        render :new
      end
    end

    def edit
        @clothing = Clothing.find(params[:clothing_id])
        @comment = Comment.find(params[:id])
        render :edit
      end

    def update
      @clothing = Clothing.find(params[:clothing_id])
      @comment = Comment.find(params[:id])
      if @comment.update(comment_params)
        flash[:notice] = "Comment Updated!"
        redirect_to clothing_path(@comment.clothing)  # Redirects to this clothing and passes in it's comments
      else
        render :edit
      end
    end

    def destroy
      @clothing = Clothing.find(params[:clothing_id])
      @comment = Comment.find(params[:id])
      @comment.destroy
      flash[:notice] = "Comment Deleted!"
      redirect_to clothing_path(@comment.clothing)#clothings_path would take you to all clothings
    end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login #this is the exception to the rule

  def new
    render :login
  end

  def create
      #try to authenticate the user - if they authenticate successfully, an instance of the User model is returned
    @user = User.authenticate(params[:email], params[:password])
      #if an instance is returned and @user is not nil...
    if @user
      #let the user know they've been logged in with a flash message
      flash[:notice] = "You've been logged in."
      #THIS IS THE MOST IMPORTANT PART. Actually log the user in by storing their ID in the session hash with the [:user_id] key!
      session[:user_id] = @user.id
      #then redirect them to the homepage
      redirect_to root_path
    else
      #whoops, either the user wasn't in the database or their password is incorrect, so let them know, then redirect them back to the log in page
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end
    def destroy
      session[:user_id] = nil
      flash[:notice] = "You've been logged out successfully."
      redirect_to "/"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login  #this is the exception to the rule

  def login
    
  end

  def signup
  end

  def new
    render :signup
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clothings/_form.html.erb
<%= form_for @clothing do |f| %>
  <%= f.label :name,'Name' %>
  <%= f.text_field :name, :class => 'form-control', :placeholder => "Name"  %><br>
  <%= f.label :details,'Details' %>
  <%= f.text_field :details, :class => 'form-control', :placeholder => "Details"  %><br>
  <%= f.label :price,'Price' %>
  <%= f.text_field :price, :class => 'form-control', :placeholder => "Price"  %><br>
  <%= f.label :image,'Image' %>
  <%= f.file_field :image %><br>
  <%= f.submit 'Save', :class => 'btn btn-warning' %>
<% end %>

app/views/clothings/edit.html.erb
<div class=" form-width">
  <h1>Edit Clothing</h1>
  <div class="well">
    <%= render "form" %>
  </div>
</div>

app/views/clothings/index.html.erb
<% if current_user.admin? %>
  <h1 class="btn btn-warning pull-right shift-down"><%= link_to "Add New Product", new_clothing_path %></h1>
<% end %>
<h1>View All Products</h1>
<div class="well-dark">
  <% if @clothings.any? %>
    <% @clothings.each do |clothing| %>
      <div class="col-sm-4">
        <div class="well-home">
          <%= link_to image_tag(clothing.image.url, :class => "image-size"), clothing_path(clothing) %>
          <span class="clothing-title"> <%= link_to clothing.name, clothing_path(clothing, :class => "clothing-text")  %></span><br>
          <span class="body-text"> Uploaded by <%= clothing.user.first_name %> <%= clothing.user.last_name %><br></span>
          <span class="body-text"><%= time_ago_in_words(clothing.created_at, :class => "time_ago" ) %> ago</span>
        </div>
      </div>
    <% end %>
    <% else %>
      <p>There are no clothings</p>
    <% end %>
</div><br>
<div class ="bar"></div>

app/views/clothings/new.html.erb
<div class=" form-width">
<h1>New Clothing </h1>
  <div class="well">
<%= render 'form' %>
  </div>
</div>

app/views/clothings/show.html.erb
<div class="well">
  <% if current_user.admin? %>
    <div class="pull-right">
      <%= link_to "Edit Clothing", edit_clothing_path %> |
      <%= link_to "Delete Clothing",  clothing_path(@clothing),  :data => {:confirm => "Are you sure?",:method => "delete"} %>
    </div>
  <% end %>
    <div class="image-box-detail">
      <%= image_tag @clothing.image.url, :class => "image-size" %>
      <h1><%= @clothing.name %></h1><br>
      <h4>Details: <%= @clothing.details %></h4>
      <h4>Price: $<%= @clothing.price %></h4>
    </div>
</div>
  <div class="btn btn-warning pull-right"><%= link_to "Add Comment", new_clothing_comment_path(@clothing) %></div>
  <span class="yellow"><h3>Comments</h3></span><br><br>
    <% if @clothing.comments.any? %>
      <ul>
        <% @clothing.comments.each do |comment| %> <!-- Loop displays all comments -->
        <li>
          <div class="well">
            <span class="clothing-text"><%= comment.content %></span><br>
            <span class="body-text ">comment by <%= comment.user.first_name %> <%= comment.user.last_name %></span>
            <div class="pull-right">
              <% if current_user === comment.user || current_user.admin? %>
              <%= link_to "Edit", edit_clothing_comment_path(@clothing, comment) %>
              <% end %>
              <% if current_user.admin? %>
        | <%= link_to "Delete", clothing_comment_path(@clothing, comment),:data =>    {:confirm => "Are you sure?",:method => "delete"} %>
              <% end %>
            </div>
        </li><br>
    <% end %>
    </ul>
    <% else %>
      <p>There are no comments yet!</p>
    </div>
    <% end %>
    <div class ="bar"></div>

app/views/comments/_form.html.erb
<%= form_for [@user, @clothing, @comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, :class => "form-control", :placeholder => "Content" %><br>
  <%= f.submit 'Save', :class => 'btn btn-warning' %>
<% end %>

app/views/comments/edit.html.erb
<div class=" form-width">
  <h1>Edit Comment</h1>
  <div class="well">
    <%= render "form" %>
  </div>
</div>

app/views/comments/new.html.erb
<div class=" form-width">
<h1>New Comment </h1>
<h3><%= @clothing.name %></h3>
  <div class="well">
<%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clothing Store</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Lobster|Open+Sans" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class = "nav navbar navbar-inverse ">
      <a href="/"><span class="brand">Clothing Store</span> </a>
      <%= link_to "Clothing", clothings_path %>
        <div class="pull-right shift-login">
        <% if current_user %>
          <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span>
          <span class="white"><%= current_user.email %></span> |
          <%= link_to "Log-out", log_out_path, method: "get" %>
        <% else %>
          <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
          <%= link_to "Log-in", log_in_path %></a> |
          <%= link_to "Signup", new_user_path %></a>
        <% end %>
      </div>
    </nav>
    <div class="container">
        <div class="alert-warning">
          <%= flash[:alert] %>
          <%= flash[:notice] %>
        </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <footer>
      Copyright 2017 Joshua Rinard
    </footer>
  </body>
</html>

app/views/users/signup.html.erb
<h1>Sign Up</h1>
<%= form_for User.new do |f| %>
<div class="form-group well">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, :class => 'form-control' %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name, :class => 'form-control' %>
  <%= f.label :email %>
  <%= f.text_field :email, :class => 'form-control' %>
  <%= f.label :password %>
  <%= f.password_field :password, :class => 'form-control' %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :class => 'form-control' %> <br>
  <%= f.submit "Sign Up", :class => 'btn'%>
<%end%>
</div>